Stub _n_noop, _nx_noop, translate_nooped_plural
Brain-WP/BrainMonkey pull request #131
Opened 2022-12-12 18:52 UTC by gmazzap

Stub for `_n_noop()`, `_nx_noop()`, and `translate_nooped_plural()` were missing in `stubTranslationFunctions()`

See #51

2022-12-13 13:11 UTC, jrfnl approved these changes
Verified against the WP functions and LGTM. Useful addition IMO.

I do see a risk with `translate_nooped_plural` potentially showing "undefined array index" notices, but I'm not concerned about that, as that would indicate a code error anyway, so if tests error out on that, all the better!

(Can I merge it or will you merge it yourself ?)

2022-12-13 13:46 UTC, jrfnl requested changes
Argh... just realized tests are missing.... sorry about that. Could you add some ?
The `FunctionsTest::testStubsTranslationsReturn()` method seems the most appropriate place.

2023-03-01 14:54 UTC, paulshryock commented
I added PR #133 which adds tests into this branch, to unblock this PR.

2023-03-06 14:50 UTC, paulshryock commented
@gmazzap let me know if PR #133 needs anything else to be merged.

2023-04-19 07:30 UTC, gmazzap commented
Thanks, @jrfnl for the review.
Thanks @paulshryock for the PR.

I think this is good to go now.

2023-04-19 07:30 UTC, merged